
setenv('SUBJECTS_DIR','/share/wandell/users/glerma/TESTDATA/FS/17_CAMINO_6835_docker/fs/output')
% ln -s $FREESURFER_HOME/subjects/fsaverage $SUBJECTS_DIR/fsaverage


pipeOutdir = '/share/wandell/users/glerma/TESTDATA/FS/17_CAMINO_6835_docker/pipeline/output432c';
subname  = 's0001';
movname  = fullfile(pipeOutdir,'RTP','mrtrix','LUF_clean_SF_fa_bin.nii.gz'); 
oname    = fullfile(pipeOutdir,'RTP','surf','LUF_clean_SF_fa_bin_projdist0.mgh'); 
oname305 = fullfile(pipeOutdir,'RTP','surf','LUF_clean_SF_fa_bin_305_projdist0.mgh'); 


movname  = fullfile(pipeOutdir,'RTP','mrtrix','LUF_clean_fa_bin.nii.gz'); 
oname    = fullfile(pipeOutdir,'RTP','surf','LUF_clean_fa_bin_projdist-1.mgh'); 
oname305 = fullfile(pipeOutdir,'RTP','surf','LUF_clean_fa_bin_305_projdist-1.mgh'); 




cmd2 =  ['mri_vol2surf ' ...
       '--srcsubject '  subname  ' ' ...
       '--projdist -1 ' ... % '--projfrac 0.5 ' ... %  
       '--interp trilinear ' ...
       '--hemi lh ' ...
       '--regheader '  subname  ' ' ...
       '--mov '  movname  ' ' ...
       '--o '  oname ...
       ];
cmd3 = ['mri_surf2surf ' ...
       '--srcsubject '  subname  ' ' ...
       '--srchemi lh ' ...
       '--srcsurfreg sphere.reg ' ...
       '--sval '  oname   ' ' ...
       '--trgsubject fsaverage ' ...
       '--trghemi rh ' ...
       '--trgsurfreg sphere.reg ' ...
       '--tval '  oname305  ' ' ...
       '--sfmt ' ...
       '--curv ' ...
       '--noreshape ' ...
       '--no-cortex ' ...
       ];

system(cmd2);
system(cmd3);


help polyxpoly

surfindv = read_surf(fullfile(getenv('SUBJECTS_DIR'),'s0001','surf','lh.inflated'));
SFindv   = read_mrtrix_tracks(fullfile(pipeOutdir,'RTP','mrtrix','LUF_clean_SF.tck'));
SFindv   = SFindv.data{1};


